# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170424_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokedwho',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poke',
            name='pokes',
            field=models.IntegerField(),
        ),
    ]
